version: '3.8'
services:
  blue:
    image: ghcr.io/cscheems/deno-task-manager:latest
    container_name: taskmanager-blue
    environment:
      - APP_ENV=BLUE
    ports:
      - "8080:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  green:
    image: ghcr.io/cscheems/deno-task-manager:latest
    container_name: taskmanager-green
    environment:
      - APP_ENV=GREEN
    ports:
      - "8081:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
