version: '3.8'
services:
  blue:
    image: ${IMAGE_NAME}
    container_name: taskmanager-blue

    ports:
      - "8080:8000"

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  green:
    image: ${IMAGE_NAME}
    container_name: taskmanager-green

    ports:
      - "8081:8000"

    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5