# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno CI/CD Blue-Green Deployment

on:
  push:
    branches: 
      - main

env:
  PROJECT_NAME: deno-task-manager
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: ghcr.io
  VPS_PROJECT_DIR: /home/deployer/deno-taskmanager
  OWNER_LC: cscheems
  HEALTHCHECK_URL: "http://localhost:8080/"

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.PROJECT_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.yml"
          target: "${{ env.VPS_PROJECT_DIR }}"
        
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -euo pipefail

            IMAGE_REPO="${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.PROJECT_NAME }}"
            PROJECT_DIR="${{ env.VPS_PROJECT_DIR }}"

            cd "$PROJECT_DIR"

            echo "==> Autenticando GHCR (si es privado)"
            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ secrets.REGISTRY_USER }}" --password-stdin

            echo "==> Haciendo pull del docker compose..."
            docker compose pull
            
            echo "==> Levantando contenedores..."
            docker compose up -d --remove-orphans

            echo "==> Iniciando Healtcheck..."

            ATTEMPTS=15
            SLEEP=3

            for attempt in $(seq 1 $ATTEMPTS); do
              if curl -fs "${{ env.HEALTHCHECK_URL }}" > /dev/null 2>&1; then
                echo "==>HEALTCHECK OK!"

                bash switch.sh
                exit 0
              fi

              sleep $SLEEP
            done
            
            echo "✖ ERROR: Healthcheck falló, deteniendo despliegue."
            docker compose logs
            exit 1

         
